name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and run tests on robot code
      id: build
      run: ./gradlew build
    - name: Apply formatting fixes
      if: steps.build.outcome == 'failure'
      run: ./gradlew spotlessApply
    - name: Formatting fix suggestions
      if: steps.build.outcome == 'failure'
      uses: googleapis/code-suggester@v2
      with:
        command: review
        pull_number: ${{ github.event.pull_request.number }}
        git_dir: '.'
