name: Suggest formatting fixes

on:
  pull_request:
    branches: [ main ]

jobs:
  suggest-formatting-fixes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check licenses
        run: ./gradlew spotlessApply
      - uses: googleapis/code-suggester@v2
        with:
          command: pr
          pull_number: ${{ github.event.pull_request.number }}
          git_dir: '.'
