name: Suggest formatting fixes

on:
  pull_request:
    branches: [ main ]

jobs:
  suggest-formatting-fixes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch all history and metadata
        run: |
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Checkout PR
        run: |
          gh pr checkout $NUMBER
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NUMBER: ${{ github.event.number }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run spotlessApply
        run: ./gradlew spotlessApply
      - name: Commit
        run: |
          # Set credentials
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Commit
          git commit -am "Formatting fixes"
          git push
